---
- name: Install Windows Updates via WSUS
  hosts: vm1
  gather_facts: true

  tasks:
    - name: Install KB3084905
      win_updates:
        kb: KB3084905
        state: installed
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        use_wsus: true

    - name: Install KB3013816
      win_updates:
        kb: KB3013816
        state: installed
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        use_wsus: true

    - name: Install KB3013769
      win_updates:
        kb: KB3013769
        state: installed
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        use_wsus: true

    - name: Install KB3102429
      win_updates:
        kb: KB3102429
        state: installed
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        use_wsus: true