- name: Install Specific Windows Updates via WSUS
  hosts: windows
  gather_facts: true

  tasks:
    - name: Install KB3084905
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        whitelist:
          - KB3084905

    - name: Install KB3013816
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        whitelist:
          - KB3013816

    - name: Install KB3013769
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        whitelist:
          - KB3013769

    - name: Install KB3102429
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        whitelist:
          - KB3102429

