- name: Install specific Windows Update with logging
  hosts: windows
  gather_facts: yes
  become: true
  become_method: runas
  become_user: Administrator

  tasks:
    - name: Run the downloaded update
      ansible.windows.win_command: >
        wusa.exe "C:\patch_update\Windows8.1-KB3102429-v2-x64.msu" /quiet /norestart
      register: patch_result
      ignore_errors: true

    - name: Log successful update without reboot
      ansible.windows.win_copy:
        content: "update installed successfully, no reboot needed"
        dest: "C:\\Users\\Administrator\\Desktop\\update.out"
      when: patch_result.rc == 0

    - name: Log successful update with reboot required
      ansible.windows.win_copy:
        content: "update installed successfully, reboot required"
        dest: "C:\\Users\\Administrator\\Desktop\\update.out"
      when: patch_result.rc == 3010

    - name: Reboot if update requires it
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: patch_result.rc == 3010
