- name: Install Specific Windows Updates via WSUS
  hosts: windows
  gather_facts: true

  tasks:
    - name: Install KB3084905
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        whitelist:
          - KB3084905
        use_wsus: true
        reboot: no

    - name: Install KB3013816
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        whitelist:
          - KB3013816
        use_wsus: true
        reboot: no

    - name: Install KB3013769
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        whitelist:
          - KB3013769
        use_wsus: true
        reboot: no

    - name: Install KB3102429
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        whitelist:
          - KB3102429
        use_wsus: true
        reboot: no
