---
- name: Print available updates and update selected packages
  hosts: all
  become: true
  vars:
    package_input: ""  # Passed via AWX survey (e.g., "bash vim")

  tasks:
    - name: Convert package_input string to list
      ansible.builtin.set_fact:
        target_packages: "{{ package_input.split() }}"

    - name: Clean yum metadata cache
      ansible.builtin.command: yum clean metadata
      changed_when: false

    - name: Run yum check-update
      ansible.builtin.command: yum check-update
      register: yum_updates
      changed_when: false
      failed_when: false

    - name: Print raw check-update output
      ansible.builtin.debug:
        msg: "{{ yum_updates.stdout_lines }}"
      when: yum_updates.stdout_lines | length > 0

    - name: Print user-selected packages
      ansible.builtin.debug:
        msg: "Updating the following packages from input: {{ target_packages }}"

    - name: Update specified packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ target_packages }}"
