- name: Install specific Windows Updates via WSUS
  hosts: windows
  gather_facts: yes

  tasks:
    - name: Install selected updates by KB number
      ansible.windows.win_updates:
        accept_list:
          - KB3084905
          - KB3013816
          - KB3013769
          - KB3102429
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2012 R2
        state: installed
        reboot: false