- name: Update selected packages from survey input
  hosts: all
  become: true
  vars:
    target_packages: []

  tasks:
    - name: Update selected packages
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ target_packages }}"
      when: target_packages | length > 0
