- name: Install specific Windows Updates via local
  hosts: windows
  gather_facts: yes
  become: true
  become_method: runas
  become_user: Administrator

  tasks:
    - name: Install the downloaded patch
      ansible.windows.win_command: >
        wusa.exe "C:\patch_update\Windows8.1-KB3102429-v2-x64.msu" /quiet /norestart
      register: patch_install_result

    - name: Display patch installation result
      debug:
        var: patch_install_result

    - name: Create log file on desktop if update was installed
      ansible.windows.win_copy:
        content: "updated success"
        dest: "C:\\Users\\Administrator\\Desktop\\update.out"
      when: patch_install_result.rc == 0