- name: Install specific Windows Updates via WSUS
  hosts: windows
  gather_facts: yes

  tasks:
    - name: Install the downloaded patch
      win_package:
        path: C:\patch_update\windows8.1-kb3102429-v2-x64_0336f192bd7bfdb01930ba46e6fdcf61b28220ed.msu
      register: patch_install_result
      
    - name: Display patch installation result
      debug:
        var: patch_install_result

    - name: Create log file on desktop if update was installed
      ansible.windows.win_copy:
        content: "updated success"
        dest: "C:\\Users\\Administrator\\Desktop\\update.out"